name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Deploy to PythonAnywhere
      env:
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
      run: |
        curl -sSL https://raw.githubusercontent.com/pythonanywhere/helper-scripts/master/deploy.sh | bash -s -- \
        --api-token $PA_API_TOKEN \
        --username yourusername \
        --project-path /home/yourusername/my-flask-app
